### ISSUE TITLE
Problem with foreign key constraint

### ISSUE THREAD

**Issue by nakoda** [UseMuffin/Footprint#49]
Its working fine with cakephp 3.5 till user is login. but how to set NULL (not 0) for not login users.

In simple words how to save fields (created_by, modified_by) with NULL not the 0.

This is the case where user can fill form with or without login and system need to track user if it is login else it should enter NULL (not zero).

**Comment by T0mi** [comment]
Same issue here. Have you find a solution for this?

**Comment by ADmad** [comment]
I assume you'll have set `DEFAULT NULL` for the foreign key field in database. Ideally if there's no logged in user that the field should either be set to `null` or not touched at all. Someone needs to figure out why/where `0` is being set for the field. Patch to fix is welcome.

**Comment by T0mi** [comment]
@ADmad so i think i've found the issue. In `FootprintBehavior.php` when injecting entity if there's no value in `$options` the `current()` funcireturns `false` so i think that's why it is trying to set the user to `0`. So i've put the check there and it's working correctly for logged in user and non-logged in user but it could break somehting else... 😄

**Comment by ADmad** [comment]
@T0mi Nice, if you can make a pull request with your chance we can review it :slightly_smiling_face:.

**Comment by T0mi** [comment]
Just did
