### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by jfalbel** [UseMuffin/Footprint#71]
Using CakePHP4
Please, review the "Usage" readme secction. I'm unable to get it working correctly. Every fail (including Missing controller or action) end with: "You must have AuthenticationComponent or AuthComponent loaded to use Footprint"

`use Muffin\Footprint\Auth\FootprintAwareTrait;

class AppController extends Controller
{
    use FootprintAwareTrait;

    // Specify the user model if required. Defaults to "Users".
    $this->_userModel = 'YourPlugin.Members';//<-- Cannot use $this out of function
}`

**Comment by jfalbel** [comment]
There is known compatibilities problem with DebugKit?

**Comment by gringlas** [comment]
I'm having the same issue. When DebugKit is activated I always recieve `You must have AuthenticationComponent or AuthComponent loaded to use Footprint`. 
I'm using ```

class AppController extends \Cake\Controller\Controller
{

    use FootprintAwareTrait {
        _setCurrentUser as _footprintSetCurrentUser;
    }

    use \Cake\ORM\Locator\LocatorAwareTrait;

    /**
     * get current user from Authentication plugin, see: https://github.com/UseMuffin/Footprint#using-footprint-with-cakephpauthentication
     */
    protected function _setCurrentUser($user = null)
    {
        if (!$user && $this->getRequest()->getAttribute('identity')) {
            $user = $this->getRequest()->getAttribute('identity')->getOriginalData();
        }

        return $this->_footprintSetCurrentUser($user);
    }

    (..)
}
```

**Comment by ADmad** [comment]
@gringlas Your code is outdated, you don't need the `_setCurrentUser()` method anymore, just `use FootprintAwareTrait`, check the updated README.

Also I don't see how a db connection error is related to the plugin.

But I think I know to fix the `You must have AuthenticationComponent or AuthComponent loaded to use Footprint` error. `FootprintAwareTrait::_setCurrentUser()` shouldn't do that check when the controller is `ErrorController`.

**Comment by gringlas** [comment]
I'm still having the issue, that when using DebugKit with Footprint, that real errors will always got consumed by `RuntimeException` in `FootprintAwareTrait` in line 110. You now check for $this->name !== 'Error', but the problem is, that even `$this` is of type `App\Controller\ErrorController` the name attribute is still the one of the controller which originally got called - in my case it is named Staticpages.
I think this is not directly related to this plugin, but I just wanted to point that out and wonder where this issue could be placed the best, as you are a cakephp core developer and might have more insights. Thank you :)

**Comment by ADmad** [comment]
That check was only meant to help Dev's but since it's causing more grief than being useful, I will just remove that check and document the fact that either of those components are required.

**Comment by jfalbel** [comment]
Well, now it's working fine. Thanks @ADmad !!
